version: 2.1

jobs:
  persist:
    parameters:
      parallel:
        type: integer
      filesize_mb:
        type: integer
    docker:
      - image: cimg/base:current
    resource_class: xlarge
    parallelism: << parameters.parallel >>
    steps:
      - run:
          name: Generate file of << parameters.filesize_mb >> MB
          command: |
            head -c $((<< parameters.filesize_mb >>*1048576)) /dev/urandom > sample.txt

            ls -lah sample.txt
      - persist_to_workspace:
          root: .
          paths:
            - sample.txt

workflows:
  file_already_closed:
    jobs:
      - persist:
          matrix:
            parameters:
              parallel:
                - 3
              filesize_mb:
                # 4.5 GB
                - 4608
                # 4.75 GB
                - 4864
                # 4.875 GB
                - 4992
